apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm1
  namespace: mq
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
    use: NonProduction
  queueManager:
    mqsc:
      - configMap:
          items:
            - DEV.QUEUE.1.mqsc
          name: mqsc-ini-example
    name: QM1
    storage:
      queueManager:
        type: persistent-claim
  version: 9.3.5.1-r1
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true