apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: get-customer-details
  namespace: ace
spec:
  apis:
    apis:
      - name: get-customer-details
  definition:
    info:
      name: GetCustomerDetails
      title: GetCustomerDetails
      version: '1.0'
    plans:
      default-plan:
        approval: false
        description: Default Plan
        rate-limits:
          default:
            value: 100/1hour
        title: Default Plan
    product: 1.0.0
  migrateSubscriptions: true
  share:
    apim:
      catalog: dev
      credentialsSecret: apim-credentials
      providerOrg: gxo
  state: Staged