
apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apiconnect-small
  name: apic
  namespace: apic
  annotations:
    apiconnect-operator/backups-not-configured: "true"
spec:
  analytics:
    mtlsValidateClient: true
  license:
    accept: true
    license: L-MMBZ-295QZQ
  metric: VIRTUAL_PROCESSOR_CORE
  use: production
  portal:
    mtlsValidateClient: true
  profile: n1xc7.m48
  version: 10.0.7.0
  storageClassName: ocs-storagecluster-ceph-rbd